# This workflow will do a clean install of node dependencies, build the source code and run tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pa11y CI

on:
  push:
    branches:
      - main

jobs:
  pa11y-ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code from ${{ github.repository }}
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      # - name: Install dependencies
      #   run: npm ci

      # - name: Start server
      #   run: ...

      - name: Install Pa11y CI and Reporters
        run: npm install -g pa11y-ci pa11y-ci-reporter-html

      - name: Execute Pa11y CI
        run: npx pa11y-ci --reporter pa11y-ci-reporter-html https://github.com/aarongoldenthal/pa11y-ci-actions-test/
        # This allows the job to not show failure if a11y issues are found
        continue-on-error: true

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Pa11y CI HTML Report
          path: ./pa11y-ci-report/*
